version: '3.9'

services: 
    db:
        image: postgres
        restart: always
        volumes: 
            - './data:/var/lig/postgresql/data'
        ports:
            - '5432:5432'
        environment: 
            POSTGRES_USER: 'admin'
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: 'crud-solid'
    adminer:
        image: adminer
        restart: always
        ports: 
            - '8080:8080'